# Generated by Django 4.0.1 on 2023-06-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registerdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField(max_length=6)),
                ('name', models.CharField(max_length=35)),
                ('dep', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=12)),
            ],
        ),
    ]
