# Generated by Django 4.0.1 on 2023-06-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdata',
            name='rollno',
            field=models.IntegerField(),
        ),
    ]
